import random


class ProceduralWorld:
    def generate_location(self):
        locations = [
            "Rust Canyon",
            "Ironveil",
            "Blackwater Harbor",
            "Steam Frontier",
            "The Underdeep",
            "Skyreach Plateau",
            "The Clockwork City",
            "The Shattered Isles",
            "The Forgotten Wastes",
            "The Ember Mountains",
            "The Crystal Caverns",
            "The Gilded Coast",
            "The Ironwood Forest",
            "The Obsidian Desert",
            "The Thunder Plains",
            "The Arcane Spire",
            "The Shadow Marshes",
            "The Celestial Peaks",
            "The Bloodstone Ruins",
            "The Phantom Isles",
            "The Eternal Glacier",
            "The Sunken Depths",
            "The Mystic Grove",
            "The Cursed Swamp",
            "The Golden Savannah",
            "The Silver Tundra",
            "The Sapphire Archipelago",
            "The Ruby Highlands",
            "The Emerald Valley",
            "The Amethyst Caverns",
            "The Topaz Desert",
            "The Onyx Mountains",
            "The Diamond Coast",
            "The Platinum Plains",
            "The Quartz Cliffs",
            "The Obsidian Fortress",
            "The Crystal Spires",
            "The Iron Citadel",
            "The Steamworks",
            "The Clockwork Tower",
            "The Arcane Academy",
            "The Shadow Fortress",
            "The Celestial Observatory",
            "The Bloodstone Keep",
            "The Phantom Castle",
            "The Eternal Library",
            "The Sunken Temple",
            "The Mystic Shrine",
            "The Cursed Monastery",
            "The Golden Palace",
            "The Silver Tower",
            "The Sapphire Fortress",
            "The Ruby Citadel",
            "The Emerald Castle",
            "The Amethyst Tower",
            "The Topaz Fortress",
            "The Onyx Castle",
            "The Diamond Tower",
            "The Platinum Fortress",
            "The Quartz Castle"
        ]

        return random.choice(locations)